sudo: false
language: python
script:
  - npm run build
install:
  - docker build -t local/history -f docker/history.docker .
  - docker build -t local/persister -f docker/persistence.docker .
services:
  - docker
after_success:
  - travis/publish.sh
