language: python
sudo: required
services:
  - mongodb
python:
  - '2.7'
install:
  - pip install -r requirements/requirements.txt -r tests/requirements.txt
  - npm install -g dredd --no-optional
before_script:
  - python setup.py install
env:
  global:
    - HISTORY_DB_ADDRESS: "localhost"

script:
  - docker build -t dojot/history -f ./docker/history.docker .
  - docker build -t dojot/persister -f ./docker/persister.docker .
  - ./tests/start-test.sh
after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
